defaults:
  - _self_
  - data: dataset
  - model: linknet
  - train: train
  - transforms: train_transforms
  - logger: wandb

seed: 42
device: cuda

model_path: ${hydra:runtime.outputs}/best_model_linknet.pth
metrics_path: ${hydra:runtime.outputs}/metrics.json