lr: 1e-3
epochs: 5
optimizer:
  _target_: torch.optim.Adam
  lr: ${..lr}
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: max
  factor: 0.5
  patience: 2
  verbose: True
  min_lr: 1e-6
loss_fn:
  _target_: torch.nn.BCEWithLogitsLoss