train:
    _target_: src.datasets.LibrispeechDataset_RU
    data_dir: /media/talium/1DA5AE943A305AF1/DataSciense/Projects/PetProjects/Audio/03. ASR/data
    split: train  # <--- Добавлено
    instance_transforms: ${transforms.instance_transforms.train}
val:
    _target_: src.datasets.LibrispeechDataset_RU
    data_dir: /media/talium/1DA5AE943A305AF1/DataSciense/Projects/PetProjects/Audio/03. ASR/data
    split: val  # <--- Добавлено
    instance_transforms: ${transforms.instance_transforms.inference}
test:
    _target_: src.datasets.LibrispeechDataset_RU
    data_dir: /media/talium/1DA5AE943A305AF1/DataSciense/Projects/PetProjects/Audio/03. ASR/data
    split: test  # <--- Добавлено
    instance_transforms: ${transforms.instance_transforms.inference}