train:
  _target_: src.project_datasets.LibrispeechDataset_RU
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.project_datasets.LibrispeechDataset_RU
  part: "dev"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.project_datasets.LibrispeechDataset_RU
  part: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
