# Конфигурация для быстрого теста (one batch test).
# Ограничивает количество примеров (limit=2) и длину аудио/текста.
# Используется dev часть датасета Librispeech.
train:
  _target_: src.datasets.LibrispeechDataset_RU
  part: "dev"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset_RU
  part: "dev"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
