_target_: src.transforms.train_transform.train_transform

horizontal_flip_p: float = 0.5
vertical_flip_p: float = 0.5
random_rotate: float = 0.5
shift_limit: float = 0.05
scale_limit: float = 0.1
rotate_limit: int = 15
shift_scale_rotate: float = 0.5
rand_bright_contrast: float = 0.2
grid_distortion: float = 0.2
mean: list = (0.3527, 0.3395, 0.2912)
std: list = (0.1384, 0.1237, 0.1199)