train_transforms:
  _target_: src.transforms.train_transforms.train_transforms
  horizontal_flip_p: 0.5
  vertical_flip_p: 0.5
  random_rotate: 0.5
  shift_limit: 0.05
  scale_limit: 0.1
  rotate_limit: 15
  shift_scale_rotate: 0.5
  rand_bright_contrast: 0.2
  grid_distortion: 0.2
  mean: [0.3527, 0.3395, 0.2912]
  std: [0.1384, 0.1237, 0.1199]

val_test_transforms:
  _target_: src.transforms.val_test_transforms.val_test_transforms
  mean: [0.3527, 0.3395, 0.2912]
  std: [0.1384, 0.1237, 0.1199]