# check the version of your pytorch, where you trained your model
# if used GPU
# Link https://hub.docker.com/r/pytorch/pytorch
FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
# workdir
WORKDIR /app

# copy requirements
COPY requirements.txt .

# install from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy all other files
COPY ./src ./src
COPY ./scripts ./scripts
COPY ./configs ./configs
COPY ./best_model_linknet.pth ./best_model_linknet.pth

ENV NVIDIA_VISIBLE_DEVICES all

# open port where will work api
EXPOSE 8000

# comand for star Uvicorn server
# --host 0.0.0.0 makes the server accessible from outside the container
CMD ["uvicorn", "scripts.api:app", "--host", "0.0.0.0", "--port", "8000"]